如何安装就略过了
# Numpy Array

In [1]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

# List 和 Numpy array 共同点

In [3]:
my_list = [1,2,3]
print(my_list[0])
print(my_list)

1
[1, 2, 3]


存储和提取就是 List 的最基本用法和功能。而 Numpy Array 也能做这件事

In [4]:
my_array = np.array([1,2,3])
print(my_array[0])
print(my_array)

1
[1 2 3]


对内部的一个值进行修改也是同样的逻辑。

In [5]:
my_list[0] = -1
my_array[0] = -1
print(my_list)
print(my_array)

[-1, 2, 3]
[-1  2  3]


# Numpy 的优势
Numpy的核心优势：运算快。   
Numpy 喜欢用电脑内存中连续的一块物理地址存储数据，因为都是连号的嘛，找到前后的号，不用跑很远， 非常迅速。而 Python 的 List 并不是连续存储的，它的数据是分散在不同的物理空间，在批量计算的时候，连号的肯定比不连号的算起来更快。因为找他们的时间更少了。

In [6]:
import time

t0 = time.time()
# python list
l = list(range(100))
for _ in range(10000):
    for i in range(len(l)):
        l[i] += 1

t1 = time.time()
# numpy array
a = np.array(l)
for _ in range(10000):
    a += 1

print("Python list spend {:.3f}s".format(t1-t0))
print("Numpy array spend {:.3f}s".format(time.time()-t1))

Python list spend 0.191s
Numpy array spend 0.016s


即使我用 map 来代替 Python 的原生循环赋值。Numpy 还是要快一些

In [7]:
import time

t0 = time.time()
# python list
l = list(range(100))
for _ in range(10000):
    l = list(map(lambda i: i+1, l))

t1 = time.time()
# numpy array
a = np.array(l)
for _ in range(10000):
    a += 1

print("Python list with map spend {:.3f}s".format(t1-t0))
print("Numpy array spend {:.3f}s".format(time.time()-t1))

Python list with map spend 0.140s
Numpy array spend 0.016s
